[build]
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate && python manage.py create_superuser_production && gunicorn gestor_vehiculos.wsgi:application"